server:
  port: 8080
  context-path: /pizzaland

spring:
  datasource:
    username: postgres
    password: root
    url: jdbc:postgresql://localhost:5432/pizzaland
  jpa:
    database: POSTGRESQL
    generate-ddl: true
    hibernate.ddl-auto: create